apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: echo-hello
  namespace: tanzu-source-controller
spec:
  imageRepositoryRef:
    name: echo-hello
  policy:
    semver:
      range: '>=0.0.0'
